### ISSUE TITLE
Getting error for ips without /32 in file.

### ISSUE THREAD

**Issue by vinod9987** [dfaerch/ip-shuffler#1]
I have file with below content -

 cat ips
192.168.1.1
192.168.1.2
192.168.1.3
192.168.1.4
192.168.1.5

While it works if I add '/32' to each of the ips, but I am getting below error if its not present as in above example -

`./ip-shuffler.py ips`
`Traceback (most recent call last):`
`  File "./ip-shuffler.py", line 49, in <module>`
`    line.append("/32")`
`AttributeError: 'str' object has no attribute 'append'`

Thanks for the script, its really helpful.

**Comment by dfaerch** [comment]
@vinod9987 thanks for the bug-report. Its fixed now.
